name: locations
services:
  app:
    container_name: locations
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6002:6002" 
      - "3345:3345" 
    env_file:     
      - .env
