FROM golang:1.23.2-alpine3.20 AS builder

WORKDIR /app

COPY . .

COPY go.mod go.sum ./

RUN go mod tidy

RUN go build -o main ./main.go

FROM alpine:3.14

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/config.json .

COPY --from=builder /app/migrations /app/migrations

EXPOSE 6002 3345

CMD ["/app/main", "-c", "/app/config.json"]
