// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: grpc/restaurants/restaurants.proto

package restaurants

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RestaurantsService_Hello_FullMethodName = "/restaurants.RestaurantsService/hello"
)

// RestaurantsServiceClient is the client API for RestaurantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantsServiceClient interface {
	Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HelloResponse, error)
}

type restaurantsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantsServiceClient(cc grpc.ClientConnInterface) RestaurantsServiceClient {
	return &restaurantsServiceClient{cc}
}

func (c *restaurantsServiceClient) Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, RestaurantsService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantsServiceServer is the server API for RestaurantsService service.
// All implementations must embed UnimplementedRestaurantsServiceServer
// for forward compatibility.
type RestaurantsServiceServer interface {
	Hello(context.Context, *Empty) (*HelloResponse, error)
	mustEmbedUnimplementedRestaurantsServiceServer()
}

// UnimplementedRestaurantsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantsServiceServer struct{}

func (UnimplementedRestaurantsServiceServer) Hello(context.Context, *Empty) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedRestaurantsServiceServer) mustEmbedUnimplementedRestaurantsServiceServer() {}
func (UnimplementedRestaurantsServiceServer) testEmbeddedByValue()                            {}

// UnsafeRestaurantsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantsServiceServer will
// result in compilation errors.
type UnsafeRestaurantsServiceServer interface {
	mustEmbedUnimplementedRestaurantsServiceServer()
}

func RegisterRestaurantsServiceServer(s grpc.ServiceRegistrar, srv RestaurantsServiceServer) {
	// If the following call pancis, it indicates UnimplementedRestaurantsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestaurantsService_ServiceDesc, srv)
}

func _RestaurantsService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantsServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantsService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantsServiceServer).Hello(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantsService_ServiceDesc is the grpc.ServiceDesc for RestaurantsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "restaurants.RestaurantsService",
	HandlerType: (*RestaurantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "hello",
			Handler:    _RestaurantsService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/restaurants/restaurants.proto",
}
