name: vehicles
services:
  app:
    container_name: vehicles
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005" 
      - "3355:3355" 
    env_file:     
      - .env