// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: grpc/posts/posts.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRestaurantIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId int32 `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
}

func (x *GetRestaurantIdReq) Reset() {
	*x = GetRestaurantIdReq{}
	mi := &file_grpc_posts_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantIdReq) ProtoMessage() {}

func (x *GetRestaurantIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_posts_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantIdReq.ProtoReflect.Descriptor instead.
func (*GetRestaurantIdReq) Descriptor() ([]byte, []int) {
	return file_grpc_posts_posts_proto_rawDescGZIP(), []int{0}
}

func (x *GetRestaurantIdReq) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

type GetRestaurantIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        bool    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RestaurantIds []int32 `protobuf:"varint,2,rep,packed,name=restaurant_ids,json=restaurantIds,proto3" json:"restaurant_ids,omitempty"`
}

func (x *GetRestaurantIdRes) Reset() {
	*x = GetRestaurantIdRes{}
	mi := &file_grpc_posts_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantIdRes) ProtoMessage() {}

func (x *GetRestaurantIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_posts_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantIdRes.ProtoReflect.Descriptor instead.
func (*GetRestaurantIdRes) Descriptor() ([]byte, []int) {
	return file_grpc_posts_posts_proto_rawDescGZIP(), []int{1}
}

func (x *GetRestaurantIdRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetRestaurantIdRes) GetRestaurantIds() []int32 {
	if x != nil {
		return x.RestaurantIds
	}
	return nil
}

type AddbranchesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId   int32 `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	RestaurantId int32 `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
}

func (x *AddbranchesReq) Reset() {
	*x = AddbranchesReq{}
	mi := &file_grpc_posts_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddbranchesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddbranchesReq) ProtoMessage() {}

func (x *AddbranchesReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_posts_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddbranchesReq.ProtoReflect.Descriptor instead.
func (*AddbranchesReq) Descriptor() ([]byte, []int) {
	return file_grpc_posts_posts_proto_rawDescGZIP(), []int{2}
}

func (x *AddbranchesReq) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *AddbranchesReq) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type AddbranchesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddbranchesRes) Reset() {
	*x = AddbranchesRes{}
	mi := &file_grpc_posts_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddbranchesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddbranchesRes) ProtoMessage() {}

func (x *AddbranchesRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_posts_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddbranchesRes.ProtoReflect.Descriptor instead.
func (*AddbranchesRes) Descriptor() ([]byte, []int) {
	return file_grpc_posts_posts_proto_rawDescGZIP(), []int{3}
}

func (x *AddbranchesRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_grpc_posts_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_posts_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_grpc_posts_posts_proto_rawDescGZIP(), []int{4}
}

func (x *HelloResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_posts_posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_posts_posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_posts_posts_proto_rawDescGZIP(), []int{5}
}

var File_grpc_posts_posts_proto protoreflect.FileDescriptor

var file_grpc_posts_posts_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2f, 0x70, 0x6f, 0x73,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x22,
	0x35, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0x56, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a,
	0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x27, 0x0a,
	0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32,
	0xc0, 0x01, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3b, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x12, 0x15,
	0x2e, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0f,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x19, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x6f, 0x73,
	0x74, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0c,
	0x2e, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x70,
	0x6f, 0x73, 0x74, 0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_posts_posts_proto_rawDescOnce sync.Once
	file_grpc_posts_posts_proto_rawDescData = file_grpc_posts_posts_proto_rawDesc
)

func file_grpc_posts_posts_proto_rawDescGZIP() []byte {
	file_grpc_posts_posts_proto_rawDescOnce.Do(func() {
		file_grpc_posts_posts_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_posts_posts_proto_rawDescData)
	})
	return file_grpc_posts_posts_proto_rawDescData
}

var file_grpc_posts_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_posts_posts_proto_goTypes = []any{
	(*GetRestaurantIdReq)(nil), // 0: posts.getRestaurantIdReq
	(*GetRestaurantIdRes)(nil), // 1: posts.getRestaurantIdRes
	(*AddbranchesReq)(nil),     // 2: posts.AddbranchesReq
	(*AddbranchesRes)(nil),     // 3: posts.AddbranchesRes
	(*HelloResponse)(nil),      // 4: posts.HelloResponse
	(*Empty)(nil),              // 5: posts.Empty
}
var file_grpc_posts_posts_proto_depIdxs = []int32{
	2, // 0: posts.PostService.addBranches:input_type -> posts.AddbranchesReq
	0, // 1: posts.PostService.getRestaurantId:input_type -> posts.getRestaurantIdReq
	5, // 2: posts.PostService.hello:input_type -> posts.Empty
	3, // 3: posts.PostService.addBranches:output_type -> posts.AddbranchesRes
	1, // 4: posts.PostService.getRestaurantId:output_type -> posts.getRestaurantIdRes
	4, // 5: posts.PostService.hello:output_type -> posts.HelloResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_posts_posts_proto_init() }
func file_grpc_posts_posts_proto_init() {
	if File_grpc_posts_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_posts_posts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_posts_posts_proto_goTypes,
		DependencyIndexes: file_grpc_posts_posts_proto_depIdxs,
		MessageInfos:      file_grpc_posts_posts_proto_msgTypes,
	}.Build()
	File_grpc_posts_posts_proto = out.File
	file_grpc_posts_posts_proto_rawDesc = nil
	file_grpc_posts_posts_proto_goTypes = nil
	file_grpc_posts_posts_proto_depIdxs = nil
}
